# Generated by Django 5.2.1 on 2025-05-28 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='tag',
        ),
        migrations.AddField(
            model_name='tag',
            name='caption',
            field=models.CharField(default='Uncategorized', max_length=100),
        ),
    ]
