# Generated by Django 5.2.1 on 2025-05-28 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_tag_caption_tag_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_name',
            field=models.CharField(default='postimg.jpeg', max_length=100),
        ),
    ]
