name: Generar documentació amb Pydoc

on:
  push:
    branches: [main]

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositori
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instal·lar dependències (si hi ha requirements.txt)
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Crear directori de documentació
        run: mkdir -p docs

      - name: Generar documentació HTML amb Pydoc
        run: |
          for module in $(find my_site blog -name "*.py" | sed 's/\.py$//' | sed 's/\//./g'); do
            python -m pydoc -w "$module"
          done
          mv *.html docs/

      - name: Publicar a GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
